"""
ingest.py
=========
RAG Ingestion Pipeline.

Steps:
    1. Load all PDFs from data/docs/  (using PyPDFLoader)
    2. Chunk them                     (using RecursiveCharacterTextSplitter)
    3. Embed + store in ChromaDB      (using Chroma.from_documents)

Run once manually:
    python rag/ingest.py

After this, the ChromaDB collection persists on disk.
The app never needs to re-ingest unless PDFs change.
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

# LangChain — PDF loading
from langchain_community.document_loaders import PyPDFLoader

# LangChain — Chunking (moved to standalone package in LangChain v0.2+)
from langchain_text_splitters import RecursiveCharacterTextSplitter

# LangChain — Embeddings (wraps sentence-transformers locally)
from langchain_community.embeddings import HuggingFaceEmbeddings

# LangChain — ChromaDB vector store
from langchain_community.vectorstores import Chroma

load_dotenv()

# ── Config ────────────────────────────────────────────────────────────────────
PROJECT_ROOT    = Path(__file__).resolve().parent.parent
DOCS_PATH       = PROJECT_ROOT / os.getenv("DOCS_PATH",  "data/docs")
CHROMA_PATH     = PROJECT_ROOT / os.getenv("CHROMA_PATH","data/chroma_db")
COLLECTION_NAME = "company_docs"
EMBEDDING_MODEL = "all-MiniLM-L6-v2"
CHUNK_SIZE      = 512
CHUNK_OVERLAP   = 100


# ── Step 1: Load PDFs ─────────────────────────────────────────────────────────
def load_documents():
    """
    Load every PDF in DOCS_PATH using PyPDFLoader.

    PyPDFLoader returns LangChain Document objects.
    Each Document has:
        page_content → raw text of that page
        metadata     → {"source": "/path/to/file.pdf", "page": 0}

    We clean up the source field to just the filename stem (e.g. "Warranty_Policy").
    """
    all_docs = []
    pdf_files = sorted(DOCS_PATH.glob("*.pdf"))

    if not pdf_files:
        raise FileNotFoundError(f"No PDFs found in: {DOCS_PATH}")

    print(f"\n[1] Loading PDFs from: {DOCS_PATH}")

    for pdf_path in pdf_files:
        loader = PyPDFLoader(str(pdf_path))
        pages  = loader.load()          # returns list of Document objects

        # Clean up metadata: use just the filename stem, not the full path
        for doc in pages:
            doc.metadata["source"]   = pdf_path.stem          # "Warranty_Policy"
            doc.metadata["page_num"] = doc.metadata.pop("page") + 1  # 0-indexed → 1-indexed

        all_docs.extend(pages)
        print(f"    [+] {pdf_path.stem} — {len(pages)} page(s)")

    print(f"    Total pages loaded: {len(all_docs)}")
    return all_docs


# ── Step 2: Chunk ─────────────────────────────────────────────────────────────
def chunk_documents(docs):
    """
    Split Document pages into smaller overlapping chunks.

    Uses RecursiveCharacterTextSplitter which tries to split on:
        1. paragraph breaks  \\n\\n
        2. line breaks       \\n
        3. sentence ends     .
        4. word boundaries   (space)
        5. characters        (last resort — never mid-word if avoidable)

    split_documents() preserves all metadata from the original Document,
    so every chunk automatically knows its source PDF and page number.

    Each chunk is still a Document object:
        page_content → chunk text  (what gets embedded)
        metadata     → {source, page_num}  (carried through from loader)
    """
    splitter = RecursiveCharacterTextSplitter(
        chunk_size      = CHUNK_SIZE,
        chunk_overlap   = CHUNK_OVERLAP,
        separators      = ["\n\n", "\n", ". ", " ", ""],
        length_function = len,
    )

    chunks = splitter.split_documents(docs)

    print(f"\n[2] Chunking complete")
    print(f"    Splitter : RecursiveCharacterTextSplitter")
    print(f"    chunk_size={CHUNK_SIZE}, overlap={CHUNK_OVERLAP}")
    print(f"    Total chunks: {len(chunks)}")

    # Show a sample chunk so we can verify metadata is intact
    if chunks:
        sample = chunks[0]
        print(f"\n    --- Sample Chunk ---")
        print(f"    page_content : \"{sample.page_content[:80]}...\"")
        print(f"    metadata     : {sample.metadata}")
        print(f"    --------------------")

    return chunks


# ── Step 3: Embed + Store in ChromaDB ─────────────────────────────────────────
def store_in_chromadb(chunks):
    """
    Convert chunks to embeddings and store in ChromaDB.

    Chroma.from_documents() does two things in one call:
        1. Calls embedding.embed_documents([chunk.page_content for chunk in chunks])
        2. Stores {ids, embeddings, documents, metadatas} in ChromaDB

    What gets stored per chunk:
        ID         → auto-generated by LangChain
        embedding  → 384-float vector of page_content
        document   → page_content (raw text — returned during retrieval)
        metadata   → {source, page_num} (for attribution)
    """
    print(f"\n[3] Loading embedding model: {EMBEDDING_MODEL}")
    embeddings = HuggingFaceEmbeddings(model_name=EMBEDDING_MODEL)

    print(f"\n[4] Storing in ChromaDB at: {CHROMA_PATH}")
    CHROMA_PATH.mkdir(parents=True, exist_ok=True)

    vectorstore = Chroma.from_documents(
        documents        = chunks,
        embedding        = embeddings,
        persist_directory= str(CHROMA_PATH),
        collection_name  = COLLECTION_NAME,
    )

    total = vectorstore._collection.count()
    print(f"    Done! {total} chunks stored in collection '{COLLECTION_NAME}'")
    return vectorstore


# ── Main ──────────────────────────────────────────────────────────────────────
def ingest(force=False):
    """
    Run the full ingestion pipeline.

    Args:
        force: If True, wipes existing collection and re-ingests.
               If False, skips if collection already has data.
    """
    # Check if already ingested
    if not force and (CHROMA_PATH / "chroma.sqlite3").exists():
        # Connect and check count
        embeddings  = HuggingFaceEmbeddings(model_name=EMBEDDING_MODEL)
        vectorstore = Chroma(
            persist_directory = str(CHROMA_PATH),
            embedding_function= embeddings,
            collection_name   = COLLECTION_NAME,
        )
        count = vectorstore._collection.count()
        if count > 0:
            print(f"\n[Skip] Collection already has {count} chunks.")
            print(f"       Use ingest(force=True) to re-ingest.")
            return vectorstore

    # Wipe old data if forcing
    if force and CHROMA_PATH.exists():
        import shutil
        shutil.rmtree(CHROMA_PATH)
        print(f"\n[Reset] Cleared existing ChromaDB at {CHROMA_PATH}")

    docs    = load_documents()
    chunks  = chunk_documents(docs)
    vectorstore = store_in_chromadb(chunks)
    return vectorstore


if __name__ == "__main__":
    force = "--force" in sys.argv
    ingest(force=force)
    print("\n[OK] Ingestion complete. ChromaDB is ready.")
